SELECT * FROM PREFEITOS;
SELECT * FROM CIDADES;

SELECT * FROM CIDADES C INNER JOIN PREFEITOS P ON C.ID = P.CIDADE_ID;
SELECT * FROM CIDADES C LEFT JOIN PREFEITOS P ON C.ID = P.CIDADE_ID;
SELECT * FROM CIDADES C RIGHT JOIN PREFEITOS P ON C.ID = P.CIDADE_ID;
-- SELECT * FROM CIDADES C FULL JOIN PREFEITOS P ON C_ID = P.CIDADE_ID;

SELECT * FROM CIDADES C LEFT JOIN PREFEITOS P ON C.ID = P.CIDADE_ID
UNION
SELECT * FROM CIDADES C RIGHT JOIN PREFEITOS P ON C.ID = P.CIDADE_ID;
